### ISSUE TITLE
Merge Operator doesn`t work

### ISSUE THREAD

**Issue by vmalyk** [pimcore/data-hub#170]
I've tested Merge operator and found next bugs:
1. It doesn't save Label for Operator
2. Title for modal isn't translated (shown  operator_merge_settings)
3. After add operator in Schema definition with 1 or more and save scheme on GraphiQL I got error:    
`Error: Must provide Array of types or a function which returns such an array for Union operator_merge.
    at invariant (https://ide.pimcore.dev.convert.no/bundles/pimcoredatahub/graphiql.min.js:12:24102)
    at defineTypes (https://ide.pimcore.dev.convert.no/bundles/pimcoredatahub/graphiql.min.js:13:29457)
    at e.getTypes (https://ide.pimcore.dev.convert.no/bundles/pimcoredatahub/graphiql.min.js:14:2913)
    at typeMapReducer (https://ide.pimcore.dev.convert.no/bundles/pimcoredatahub/graphiql.min.js:15:1393)
    at typeMapReducer (https://ide.pimcore.dev.convert.no/bundles/pimcoredatahub/graphiql.min.js:15:1137)
    at https://ide.pimcore.dev.convert.no/bundles/pimcoredatahub/graphiql.min.js:15:1779
    at Array.forEach (<anonymous>)
    at https://ide.pimcore.dev.convert.no/bundles/pimcoredatahub/graphiql.min.js:15:1661
    at typeMapReducer (https://ide.pimcore.dev.convert.no/bundles/pimcoredatahub/graphiql.min.js:15:1806)
    at Array.reduce (<anonymous>)`

**Comment by weisswurstkanone** [comment]
Fixed 1) and 2)

Can you provide a very simple example for 3) ?

**Comment by vmalyk** [comment]
@weisswurstkanone , I've setup example on demo.pimcor.fun.

1)Added Merge to Schema definition and add some children:
![Скриншот 2020-03-12 17 20 06](https://user-images.githubusercontent.com/5318027/76531553-6cae9f00-6486-11ea-9439-2ce8bb7b281e.png)

2) Save schema  and try to open for testing. You get error:
![Скриншот 2020-03-12 17 20 45](https://user-images.githubusercontent.com/5318027/76531631-8c45c780-6486-11ea-9fa1-d82b307a4389.png)

**Comment by weisswurstkanone** [comment]
Ok, the Merge type was primarily intented for merging multiple arrays.

In your case: what what be expectation? If I see it correctly you are trying to merge two quantity value fields ?

**Comment by vmalyk** [comment]
so, Based on you description it works with array values - many-to-many relations, fieldcollections, etc.

Based on availability to use different I expected to get object field and It contains values from children fields: For ex. :
```
Merge: {
     Weight: 0.23,
     Weelbase: 'some base' 
} 
```

**Comment by weisswurstkanone** [comment]
No, then this is a misunderstanding. But would be a nice idea for a new operator.
