### ISSUE TITLE
No Schema available in iExplorer

### ISSUE THREAD

**Issue by Zielgestalt** [pimcore/data-hub#184]
When opening a data-hub config in iExplorer no schema or docs are available. Error message: 

```
Error: Must provide Array of types or a function which returns such an array for Union document_tree.
    at invariant (https://demo.pimcore.fun/bundles/pimcoredatahub/graphiql.min.js:12:24102)
    at defineTypes (https://demo.pimcore.fun/bundles/pimcoredatahub/graphiql.min.js:13:29457)
    at e.getTypes (https://demo.pimcore.fun/bundles/pimcoredatahub/graphiql.min.js:14:2913)
    at typeMapReducer (https://demo.pimcore.fun/bundles/pimcoredatahub/graphiql.min.js:15:1393)
    at https://demo.pimcore.fun/bundles/pimcoredatahub/graphiql.min.js:15:1779
    at Array.forEach (<anonymous>)
    at https://demo.pimcore.fun/bundles/pimcoredatahub/graphiql.min.js:15:1661
    at typeMapReducer (https://demo.pimcore.fun/bundles/pimcoredatahub/graphiql.min.js:15:1806)
    at Array.reduce (<anonymous>)
    at typeMapReducer (https://demo.pimcore.fun/bundles/pimcoredatahub/graphiql.min.js:15:1404)
```

You can easily recreate this on https://demo.pimcore.fun/admin

**Comment by NiklasBr** [comment]
I got that error message in Firefox also, not just IE

**Comment by Zielgestalt** [comment]
Sorry, with 'IExplorer' I meant the GraphQL-Tool - not the browser :-) Same in GraphiQL.

**Comment by weisswurstkanone** [comment]
regression of https://github.com/pimcore/data-hub/commit/8a4dfc2c8476d0c61b360de369ab6a2bf69342aa
