### ISSUE TITLE
master broken: Error: Must provide Array of types or a function which returns such an array for Union hotspot_metadata_object.

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/data-hub#185]
Just installed master and it seems to be broken, when I open the GraphQL Editor it shows:

```
Error: Must provide Array of types or a function which returns such an array for Union hotspot_metadata_object.
    at invariant (http://localhost:4000/bundles/pimcoredatahub/graphiql.min.js:12:24102)
    at defineTypes (http://localhost:4000/bundles/pimcoredatahub/graphiql.min.js:13:29457)
    at e.getTypes (http://localhost:4000/bundles/pimcoredatahub/graphiql.min.js:14:2913)
    at typeMapReducer (http://localhost:4000/bundles/pimcoredatahub/graphiql.min.js:15:1393)
    at http://localhost:4000/bundles/pimcoredatahub/graphiql.min.js:15:1779
    at Array.forEach (<anonymous>)
    at http://localhost:4000/bundles/pimcoredatahub/graphiql.min.js:15:1661
    at typeMapReducer (http://localhost:4000/bundles/pimcoredatahub/graphiql.min.js:15:1806)
    at Array.reduce (<anonymous>)
    at typeMapReducer (http://localhost:4000/bundles/pimcoredatahub/graphiql.min.js:15:1404)
```

**Comment by dpfaffenbauer** [comment]
Ok, bit more context:

I only enabled documents, without any object scheam

**Comment by NiklasBr** [comment]
We noted it a few days ago and this appears to have something to do with Generic Types in the configuration, checking them resolved the issue for us.
