### ISSUE TITLE
[Bug][1.x with Pimcore 10.6] IExplorer open in Tab fails

### ISSUE THREAD

**Issue by fashxp** [pimcore/data-hub#742]
### Expected behavior

can open iexplorer in tab

### Actual behavior

```
[2023-05-04T19:48:17.945571+00:00] request.CRITICAL: Uncaught PHP Exception LogicException: "Cannot register a bag when the session is already started." at /var/www/html/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php line 334 {"exception":"[object] (LogicException(code: 0): Cannot register a bag when the session is already started. at /var/www/html/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:334)"} []
[2023-05-04T19:48:17.946089+00:00] app.ERROR: LogicException: Cannot register a bag when the session is already started. in /var/www/html/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:334 Stack trace: #0 /var/www/html/vendor/symfony/http-foundation/Session/Session.php(253): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->registerBag(Object(Symfony\Component\HttpFoundation\Session\SessionBagProxy)) #1 /var/www/html/vendor/pimcore/openid-connect/src/EventListener/OpenIdSessionBagListener.php(58): Symfony\Component\HttpFoundation\Session\Session->registerBag(Object(Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag)) #2 /var/www/html/vendor/pimcore/openid-connect/src/EventListener/OpenIdSessionBagListener.php(46): Pimcore\Bundle\OpenIdConnectBundle\EventListener\OpenIdSessionBagListener->configure(Object(Symfony\Component\HttpFoundation\Session\Session)) #3 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(270): Pimcore\Bundle\OpenIdConnectBundle\EventListener\OpenIdSessionBagListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\RequestEvent)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(139): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request') #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 {main} [] []
```

### Steps to reproduce

- Install Pimcore 10.6 with datahub
- create new enpoint
- open iexporer in new tab 

--> open iexplorer in iframe works

only happens when OpenIDConnect bundle is active

see also https://github.com/pimcore/openid-connect/issues/75

**Comment by kingjia90** [comment]
Resolved by https://github.com/pimcore/openid-connect/pull/79
